### ISSUE TITLE
protocol.map is incorrect or not correctly formated (map2)

### ISSUE THREAD

**Issue by Lojza007** [quadrantsec/sagan-rules#165]
With default config I can't start Sagan. If I swap to old protocol.map, it'll start. Probably misconfigured but I wasn't able to find solution in Sagan User Guide.

**Comment by quadrantsec** [comment]
We converted the protocol map to JSON.   Are you attempting to us the stable version of Sagan with the Github signatures? That would likely be the issue.   Github signatures (ie - non-stable) work best with Github Sagan (non-stable).

**Comment by Lojza007** [comment]
I've installed Github version 2.0.2. Downloaded older version of signatures and noticed they were moved here. Maybe there should be notice for BFU like me which version of signatures should I install.

**Comment by quadrantsec** [comment]
You are correct.  We need to state this more clearly in the docuements.

**Comment by quadrantsec** [comment]
I'm going to leave this open until this is better documented.   Thank you.
