### ISSUE TITLE
EventID in some RDP signatures might be wrong?

### ISSUE THREAD

**Issue by CyberTaoFlow** [quadrantsec/sagan-rules#2]
I noticed several RDP sigs are matching event id 4724 instead of 4624.
4724 -> An attempt was made to reset an account's password
4624 -> An account was successfully logged on.
 

windows-auth.rules:#alert any $HOME_NET any -> $EXTERNAL_NET any (msg: "[WINDOWS-AUTH] RDP / Logon type 10"; event_id: 4724,528; content: "Logon Type|3a| 10 "; program: *Security*; parse_src_ip: 1; default_proto: tcp; classtype: successful-user; reference: url,wiki.quadrantsec.com/bin/view/Main/5002015; sid: 5002015; rev:6;)

windows-auth.rules:alert any $HOME_NET any -> $EXTERNAL_NET any (msg: "[WINDOWS-AUTH] Login via RDP from a suspicious user"; event_id: 4724,528; content: "Logon Type|3a| 10 "; meta_content: "Account Name|3a| %sagan%",guest,administrator,sql,demo,db2admin,pos,accounting,letmein,mysql,oracle,test,testing,support,sales,ansible,ec2-user,azureuser; meta_nocase; program: *Security*; parse_src_ip: 1; default_proto: tcp; classtype: successful-user; reference: url,wiki.quadrantsec.com/bin/view/Main/5003981; sid:5003981; rev:2;)

windows-blacklist.rules:alert any $HOME_NET any -> $EXTERNAL_NET any (msg: "[WINDOWS-BLACKLIST] RDP / Logon type 10 from a blacklisted IP"; program: *Security*; event_id: 4724,528,540; content: "Logon Type|3a| 10 "; blacklist: by_src; program: *Security*; parse_src_ip: 1; normalize; default_proto: tcp; classtype: successful-user; reference: url,wiki.quadrantsec.com/bin/view/Main/5002215; sid: 5002215; rev:6;)

**Comment by quadrantsec** [comment]
Whoa. Let me research this a bit...

**Comment by quadrantsec** [comment]
Nice catch and thank you!  I've made the changes to those rules.  It looks like a "copy and paste" thing happened.  I pushed and update to github.
