### ISSUE TITLE
Duplicate SIDs for SentinelOne and TrendMicro

### ISSUE THREAD

**Issue by MigNov** [quadrantsec/sagan-rules#90]
Hello,
I've found a duplicate SID within your rule files. There's SID 5006615 for both sentinelone.rules and trendmicro.rules.
I don't know whether you have any SID assignment convention so I'm just reporting the issue without a patch not to use different range than you'd use yourself.

Could you please fix it?

Thanks a lot,
Michal

**Comment by quadrantsec** [comment]
Thank you.  We will get this fixed asap !
________________________________
From: Michal Novotny ***@***.***>
Sent: Thursday, September 8, 2022 4:50:40 AM
To: quadrantsec/sagan-rules ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [quadrantsec/sagan-rules] Duplicate SIDs for SentinelOne and TrendMicro (Issue #90)


Hello,
I've found a duplicate SID within your rule files. There's SID 5006615 for both sentinelone.rules and trendmicro.rules.
I don't know whether you have any SID assignment convention so I'm just reporting the issue without a patch not to use different range than you'd use yourself.

Could you please fix it?

Thanks a lot,
Michal

**Comment by wrharding** [comment]
I believe this was fixed some time ago and can be closed.

**Comment by MigNov** [comment]
Yeah, it's been fixed 3 months ago in commit 74e973f5 so feel free to close it :-)
Thanks a lot!
